// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryxmobnjjmvwchqcjmup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5eG1vYm5qam12d2NocWNqbXVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5MTA5MDQsImV4cCI6MjA1MjQ4NjkwNH0.ZqeBbaPC7gHKmmmDgernDsxIeOWR78eciBBOVkNUFHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);